version: '3'  # version of compose format

services:
  backend-py:
    build:
      context: ./_docker-files
      dockerfile: ./PyDockerfile
    volumes:
      - ./backend-py/:/usr/src/app # mount point
    ports:
      - 5001:80  # host:container

  website:
    image: php:apache  # pulling image from DockerHub
    volumes:
      - ./frontend/:/var/www/html # mount
    ports:
      - 5000:80  # host:container
    depends_on:
      - backend-py  # website is not going to work
                    # unless backend-py is running

  postgresql:
    image: docker.io/bitnami/postgresql:12
    ports:
      - '5432:5432' # host:container
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'

volumes:
  postgresql_data:
    driver: local